export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export  const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export  const LOGOUT = "LOGOUT"

export const INVITE_REQUEST = "INVITE_REQUEST"
export const INVITE_FAILURE = "INVITE_FAILURE"
export  const INVITE_SUCCESS = "INVITE_SUCCESS"

export const GET_SUPERUSER_COMPANY_REQUEST = "GET_SUPERUSER_COMPANY_REQUEST"
export const GET_SUPERUSER_COMPANY_FAILURE = "GET_SUPERUSER_COMPANY_FAILURE"
export  const GET_SUPERUSER_COMPANY_SUCCESS = "GET_SUPERUSER_COMPANY_SUCCESS"
